### PR TITLE
Update the package to meet new standard

### PR DESCRIPTION
**Pull request by HJ08003**
(1) Used reverse engineering approach to add Roxygen comments to *.R
(2) Generated *.md from *.R using Roxygen2
(3) Added importFrom to NAMESPACE
(4) Added src/init.c for C routines registration
(5) Added .travis.yml for automatic check at travis.org

It passed travis-ci check. 

However, there was a WARNING for lack of examples etc. when I did "R CMD check --as-cran". The win-builder also report that WARNING. Other than that, the package should be fine.

### CODE REVIEW

**Comment by kosukeimai** [comment]
@HJ08003 Can you autogenerate `NAMESPACE` as well?

**Comment by HJ08003** [comment]
It is done, and passed travis-ci check.

**Comment by kosukeimai** [comment]
@HJ08003 Please check the win-builder too.  Thanks.

**Comment by HJ08003** [comment]
Below is feedback from win-builder. The NOTE is for that I put my email to receive the feedback, and the WARNING is for no examples in the package.



On 9/28/17, 5:18 PM, "Uwe.Ligges@r-project.org" <Uwe.Ligges@r-project.org> wrote:

Dear package maintainer,
this notification has been generated automatically.
Your package experiment_1.1-2.tar.gz has been built (if working) and checked for Windows.
Please check the log files and (if working) the binary package at:
https://win-builder.r-project.org/WuWYhzWhMQ96
The files will be removed after roughly 72 hours.
Installation time in seconds: 32
Check time in seconds: 56
Status: 1 WARNING, 1 NOTE
R version 3.4.2 (2017-09-28)
All the best,
Uwe Ligges
(CRAN maintainer of binary packages for Windows)

**Pull request merged**
